c/README.asciidoc, c/reverse/build.sh, c/reverse/reverse.c
This DFINITY app can be built using standard tools alone.
=> Add `reverse` example.

qr/README.adoc, qr/build.sh, qr/qr.c, reverse/build.sh, reverse/reverse.c
Fix compilation warnings in `reverse` demo.
=> Add QR code example.

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, motoko/favorite_cities/src/favorite_cities/public/index.js
=> Docs: Prepare repo for public

motoko/hello-world/README.md, motoko/hello-world/src/main.mo
**Overview**
As reported in https://github.com/dfinity/examples/issues/40, this example and instructions are out-of-date.
We are sending people to this repo so we should make sure the examples work.
=> Fix hello-world source and README to work

motoko/simple_to_do/README.md
**Overview**
Looks like all of the examples need to be updated.
=> Add the register step

motoko/calc/dfx.json, motoko/simple_to_do/dfx.json
update dfx version to `0.6.6` so example runs without error
=> update dfx version so example runs without error

motoko/simple_to_do/src/simple_to_do/utils.mo
(Follow latest argument order style: We decided to place the order of arguments that are themselves functions at the end.)
=> Update Simple_to_do for latest Base

motoko/calc/README.md
=> Add a badge for compatibility

motoko/phone-book/package-lock.json, motoko/phone-book/package.json, motoko/phone-book/webpack.config.js
**Overview**
We need to remove any vulnerabilities from this codebase as it gives the impression that our code is not being maintained.
Remove the `TerserWebpackPlugin`.
=> Remove vulnerable Terser plugin

motoko/phone-book/README.md, motoko/superheroes/README.md
Before build the canister,  build the React file.
=> Update phone-book README.md

.github/workflows/provision-darwin.sh, .github/workflows/provision-linux.sh, motoko/calc/dfx.json, motoko/counter/dfx.json, motoko/echo/dfx.json, motoko/factorial/dfx.json, motoko/hello-world/dfx.json, motoko/hello_cycles/dfx.json, motoko/life/dfx.json, motoko/life/package.json, motoko/phone-book/dfx.json, motoko/phone-book/package.json, motoko/pub-sub/dfx.json, motoko/quicksort/dfx.json, motoko/simple-to-do/dfx.json, motoko/superheroes/dfx.json, motoko/superheroes/package.json, motoko/whoami/dfx.json
=> update to 0.7.0-beta.6

motoko/random_maze/README.md
=> Update README.md (fix typo)

motoko/counter/README.md, motoko/counter/src/Main.mo, motoko/phone-book/src/phone-book/Main.mo, motoko/random_maze/src/random_maze/main.mo
* `phone-book`: Remove AssocList
* `random-maze`: Fix inferred Nat type warning
* `counter`: make counter stable
=> fix examples

wasm/counter/counter.wat
With this being an example for public consumption, I couldn't resist. :)
=> More idiomatic Wasm style

motoko/encrypted-notes-dapp/src/encrypted_notes_motoko/main.mo
=> experiment: Motoko bug workaround

rust/exchange_rate/README.md
=> Editorial changes

rust/exchange_rate/src/main.rs
This is a minor typo fixing PR.
=> Fix a couple of typos

motoko/phone-book/README.md, motoko/phone-book/package-lock.json, motoko/phone-book/package.json, motoko/phone-book/webpack.config.js
Fixing issues with the Motoko phone book dapp caused by upgrading to dfx 0.11.1. Also made some minor documentation fixes for simplification.
I removed the generated declarations because we don't commit them in the other projects. I can go back and generate them for the other projects if we'd like to include them and be consistent.
=> fix duplicate assets exception for motoko phone book

motoko/minimal-counter-dapp/README.md, motoko/minimal-counter-dapp/package-lock.json, motoko/minimal-counter-dapp/package.json, motoko/minimal-counter-dapp/src/minimal_dapp_assets/assets/main.css, motoko/minimal-counter-dapp/src/minimal_dapp_assets/src/index.js, motoko/minimal-counter-dapp/webpack.config.js
Fixing issues with the Motoko minimal counter dapp caused by upgrading to dfx 0.11.1. Also made some minor code style fixes for consitency.
=> fix duplicate assets exception for motoko minimal counter dapp

motoko/basic_dao/README.md, rust/basic_dao/README.md
Add security considerations for DAO examples
This is one of many PRs adding links to security best practices
=> Add security considerations for DAO example

motoko/basic_bitcoin/README.md, rust/basic_bitcoin/README.md
Add security considerations for Bitcoin example
This is one of many PRs adding links to security best practices
=> Add security considerations for Bitcoin example

motoko/counter/README.md
Add security considerations for counter example. Only adds a general reference since this doesn't seem to be a very security sensitive topic.
=> Add security considerations for counter example

motoko/defi/README.md
Add security considerations, link best practices and add examples for DEFI example
=> Add security considerations for defi example

motoko/classes/README.md
Add security considerations for classes example. Only adds a general reference since this doesn't seem to be a very security sensitive topic.
=> Add security considerations for classes example

motoko/cert-var/README.md
This adds security best practices and examples for the cert-var example
=> Add security considerations for cert-var example

motoko/calc/README.md
Adds security best practices link and examples for the Motoko Calc example.
=> Add security considerations for Calc example

.github/workflows/rust-basic-bitcoin-example.yml, motoko/dip721-nft-container/README.md, rust/dip721-nft-container/README.md
Add security best practices reference to docs for NFT example
=> Add security best practices reference to docs for NFT example

motoko/echo/README.md, rust/counter/README.md
Add security best practices link to docs for echo and counter example
=> Add security best practices link to docs for echo and counter example

motoko/exchange_rate/README.md, rust/exchange_rate/README.md
Add security best practices link to docs for exchange rate example
=> Add security best practices link to docs for exchange rate example

motoko/hello-world/README.md, motoko/hello_cycles/README.md
Add security best practices link to docs for hello world and hello cycles
=> Add security best practices link to docs for hello world and hello cycles

motoko/http_counter/README.md
Add security best practices link to docs for http counter
=> Add security best practices link to docs for http counter

motoko/invoice-canister/README.md
Add security best practices link to docs for the invoice canister
=> Add security best practices link to docs for the invoice canister

motoko/ledger-transfer/README.md
Add security best practices link to docs for the ledger transfer
=> Add security best practices link to docs for the ledger transfer

motoko/life/README.md
Add security best practices link to docs for the life example
=> Add security best practices link to docs for the life example

rust/exchange_rate/src/main.rs
Reported on the [Forum](https://forum.dfinity.org/t/how-to-update-this-simple-example-for-new-http-transform/16455/3) as being the wrong URL
=> Switch to free coinbase API

README.md, motoko/README.md, motoko/whoami/README.md, rust/tokens_transfer/README.md, svelte-motoko-starter/README.md, svelte-starter/README.md
Add security best practices link to docs for whoami, token transfer, svelte and general overview docs
=> Add security best practices link to docs for whoami, token transfer, svelte and general overview docs

motoko/quicksort/README.md, motoko/random_maze/README.md, motoko/simple-to-do/README.md, motoko/superheroes/README.md, motoko/threshold-ecdsa/README.md, rust/threshold-ecdsa/README.md
Add security best practices link to docs for quicksort, maze, todo, heroes, ecdsa
=> Add security best practices link to docs for quicksort, maze, todo, heroes, ecdsa

motoko/basic_bitcoin/README.md, rust/basic_bitcoin/README.md
* Fix broken link
**Overview**
=> Bitcoin GA release

.gitmodules
This PR should redo the submodules links to II from the Svelte (rollup) examples that went lost in previous refactoring PR #388.
=> chore: redo svelte examples ii submodules

motoko/basic_bitcoin/README.md, motoko/basic_bitcoin/dfx.json
**Overview**
- updated readme to point to local and production deployment
- removed unnecessary entries in `dfx.json` (see https://github.com/dfinity/portal/pull/1011)
=> 📝 updated README and removed dfx.json entries

motoko/hello_cycles/README.md
=> Update README.md hello_cycles example

motoko/invoice-canister/README.md
=> Update README.md Invoice canister

motoko/basic_bitcoin/README.md
=> chore: updating basic_bitcoin readme

motoko/actor_reference/README.md
=> chore: updating readme for actor reference

motoko/calc/README.md
=> chore: update calc

motoko/cert-var/README.md, motoko/cert-var/package.json
=> chore: updating cert-var example

motoko/counter/README.md
=> chore: updating counter example

motoko/classes/README.md
=> chore: updating classes example

motoko/dip721-nft-container/README.md, motoko/dip721-nft-container/demo.sh
=> chore: update dip721-nft-container

motoko/echo/README.md
=> chore: update echo

motoko/encrypted-notes-dapp/README.md, motoko/invoice-canister/docs/bounty-task-checklist.md, svelte/svelte-motoko-starter/README.md
=> Additional image/link fixes

motoko/cert-var/README.md, motoko/encrypted-notes-dapp-vetkd/README.md, motoko/ic-pos/README.md, motoko/invoice-canister/README.md, motoko/invoice-canister/docs/bounty-task-checklist.md, motoko/vetkd/README.md, svelte/sveltekit-starter/README.md
=> Fix links Docusaurus identifies as broken

motoko/ic-pos/README.md, motoko/invoice-canister/docs/bounty-task-checklist.md, rust/vetkd/README.md
=> More broken links

motoko/encrypted-notes-dapp-vetkd/README.mdx, motoko/invoice-canister/docs/bounty-task-checklist.md
=> fix: more updates of .md -> .mdx

rust/defi/README.md
**Overview**
The referenced images were missing leading to the portal not building successfully.
once this is merged, update the submodule in the portal
=> 🩹 remove missing images

motoko/token_transfer_from/README.md, rust/token_transfer_from/README.md
**Overview**
wrong content in transfer from readme
=> ✏️ fixed README

native-apps/unity_ii_applink/README.md, native-apps/unity_ii_deeplink/README.md, native-apps/unity_ii_universallink/README.md
=> Update docs format for native dapps

motoko/dip721-nft-container/README.md, motoko/encrypted-notes-dapp/README.md, rust/dip721-nft-container/README.md, rust/encrypted-notes-dapp/README.md
=> Fix Motoko docs links

ADDING_AN_EXAMPLE.md
=> 🩹 add more docs

.github/workflows/provision-darwin.sh, .github/workflows/update-ic-commit.yml
Clone of https://github.com/dfinity/examples/pull/565
=> chore: update node version

motoko/icp_transfer/README.md, motoko/token_transfer/README.md, motoko/token_transfer_from/README.md, rust/icp_transfer/README.md, rust/token_transfer/README.md, rust/token_transfer_from/README.md
=> chore: Replace GItHub formatted alerts/info boxes

rust/threshold-ecdsa/src/ecdsa_example_rust/src/lib.rs
Updated the sample code to use the functions and types provided by ic-cdk.
=> Use management canister API provided by ic-cdk

motoko/auth_client_demo/package-lock.json, motoko/life/package-lock.json, motoko/minimal-counter-dapp/package-lock.json, motoko/phone-book/package-lock.json, motoko/random_maze/package-lock.json, motoko/send_http_get/package-lock.json, motoko/send_http_post/package-lock.json, motoko/superheroes/package-lock.json, motoko/vetkd/Cargo.lock, motoko/vetkd/package-lock.json, rust/hello/package-lock.json
=> chore: resolve dependabot alerts

motoko/superheroes/README.md
=> Fix typo on README

motoko/encrypted-notes-dapp-vetkd/package-lock.json, motoko/encrypted-notes-dapp/package-lock.json, motoko/hello/package-lock.json, motoko/life/package-lock.json, motoko/minimal-counter-dapp/package-lock.json, motoko/phone-book/package-lock.json, motoko/random_maze/package-lock.json, motoko/send_http_post/package-lock.json, motoko/superheroes/package-lock.json
Resolves dependabot reported security issues
=> chore: update ws dep to resolve security issues

motoko/defi/src/frontend/README.md, rust/defi/src/frontend/README.md
=> fix: update broken links

motoko/http_counter/README.md
=> fix: link to security best practices regarding HTTP asset certification

.github/workflows/provision-darwin.sh, .github/workflows/provision-linux.sh
=> chore: promote dfx 0.23.0

motoko/basic_bitcoin/README.md
=> add: explicit statement about running basic_bitcoin on mainnet

rust/basic_bitcoin/README.md
The motoko example now also supports taproot.
=> update rust basic_bitcoin readme

.github/workflows/rust-face-recognition-example.yaml, rust/face-recognition/dfx.json
=> chore: remove outdated dfx in jobs of face recognition example

.github/workflows/close-stale-issues.yaml
@marc0olo thanks for suggesting this
=> chore: extend stale issues timeframe

rust/basic_bitcoin/src/basic_bitcoin/src/lib.rs
**Overview**
Updates wrong information in code comments.
=> docs: mainnet is supported

.github/workflows/rust-parallel-calls-example.yml, rust/parallel_calls/Cargo.lock, rust/periodic_tasks/Makefile
This PR fixes broken cargo build of `rust/parallel_calls` and flaky test of `rust/periodic_tasks`.
=> fix: broken build and test

rust/threshold-mock/CONTRIBUTING.md
=> remove: unused link

.github/CODEOWNERS, motoko/ic-pos/package-lock.json, motoko/ic-pos/package.json, motoko/ic-pos/src/icpos_frontend/canisters/ckbtc-index/hooks/useCkBtcIndex.tsx, motoko/ic-pos/src/icpos_frontend/canisters/ckbtc-ledger/hooks/useCkBtcLedger.tsx, motoko/ic-pos/src/icpos_frontend/canisters/ckbtc-ledger/hooks/useCkBtcLedgerAnon.tsx, motoko/ic-pos/src/icpos_frontend/canisters/icrc/types/transfer.type.ts, motoko/ic-pos/src/icpos_frontend/pages/history/HistoryPage.tsx, motoko/ic-pos/src/icpos_frontend/pages/history/components/TransactionRow.tsx
Replace the deprecated @dfinity/ledger dependency with the latest @dfinity/ledger-icrc.
=> chore(ic_pos): FI-1587: Change ICRC ledger library dependency

motoko/basic_bitcoin/README.md, motoko/threshold-ecdsa/README.md, motoko/threshold-schnorr/README.md, rust/basic_bitcoin/README.md, rust/basic_ethereum/README.md, rust/threshold-ecdsa/README.md, rust/threshold-schnorr/README.md, rust/x509/README.md, svelte/svelte-motoko-starter/README.md, svelte/svelte-starter/README.md, svelte/sveltekit-starter/README.md
relies on https://github.com/dfinity/portal/pull/3768
=> docs: remove mentioning free cycles

hosting/photo-storage/package-lock.json, hosting/photo-storage/src/App.js
=> fix: deprecated constructor & permission error

.github/CODEOWNERS
=> update codeowner of iii example

svelte/svelte-starter/README.md
=> fix: svelte-starter readme

.github/workflows/examples_pr_checks.yml, rust/backend_only/files.json
removes an unused file
also fixes CI to only run changed things - check runs on PRs against `master`, but checks diff against `main`
=> chore: rm unused file, fix CI

rust/basic_bitcoin/README.md
Some small updates to the basic bitcoin README.md file, including:
- Testnet3 > Testnet4
- Additional pre-requisite info in case build does not work
- Stale links updated
=> Update README.md for Basic Bitcoin example

motoko/README.md
Removed bunch of broken links to missing example projects
=> Remove broken links to missing examples

hosting/static-website/README.md
**Overview**
The README is inaccurate based on the dfx.json in this project.
=> chore: Fix the port number of the canister url

.github/workflows/motoko-hello_cycles-example.yaml, .github/workflows/provision-darwin.sh, .github/workflows/provision-linux.sh, .github/workflows/rust-composite_query-example.yml, .github/workflows/rust-parallel-calls-example.yml, motoko/classes/Makefile, motoko/classes/README.md, motoko/composite_query/Makefile, motoko/composite_query/README.md, motoko/hello_cycles/Makefile, motoko/icrc2-swap/package-lock.json, motoko/icrc2-swap/package.json, motoko/icrc2-swap/test/swap/agent.ts, motoko/parallel_calls/Makefile, motoko/parallel_calls/README.md, motoko/threshold-ecdsa/src/ecdsa_example_motoko/main.mo, motoko/threshold-schnorr/src/schnorr_example_motoko/main.mo, rust/composite_query/README.md, rust/composite_query/src/kv_frontend/lib.rs, rust/inter-canister-calls/README.md, rust/inter-canister-calls/src/caller/src/lib.rs, rust/nft-wallet/deploy.sh, rust/nft-wallet/frontend/package-lock.json, rust/nft-wallet/start.sh, rust/parallel_calls/Makefile, rust/parallel_calls/README.md
Includes https://github.com/dfinity/examples/pull/973
=> chore: promote dfx to 0.26.0

ADDING_AN_EXAMPLE.md
=> update: ADDING_AN_EXAMPLE.md

.github/CODEOWNERS, rust/backend_wasm64/README.md
- add open in icp ninja button to wasm64 example
- add ninja devs to CI job as codeowners
=> chore: Add Open in ICP Ninja button to Wasm64 example

rust/basic_bitcoin/README.md, rust/basic_bitcoin/dfx.json
- Updated the README to better align with the new Bitcoin dev docs
- Removed unnecessary settings from `dfx.json`
=> README updates basic_bitcoin

rust/inter-canister-calls/README.md
=> add: Deploy to ICP Ninja + standardize README

.github/workflows/ninja_pr_checks.yml, hosting/my_crypto_blog/.devcontainer/devcontainer.json, hosting/react/.devcontainer/devcontainer.json, motoko/backend_only/.devcontainer/devcontainer.json, motoko/daily_planner/.devcontainer/devcontainer.json, motoko/evm_block_explorer/.devcontainer/devcontainer.json, motoko/filevault/.devcontainer/devcontainer.json, motoko/flying_ninja/.devcontainer/devcontainer.json, motoko/hello_world/.devcontainer/devcontainer.json, motoko/tokenmania/.devcontainer/devcontainer.json, motoko/who_am_i/.devcontainer/devcontainer.json, rust/backend_only/.devcontainer/devcontainer.json, rust/daily_planner/.devcontainer/devcontainer.json, rust/evm_block_explorer/.devcontainer/devcontainer.json, rust/flying_ninja/.devcontainer/devcontainer.json, rust/hello_world/.devcontainer/devcontainer.json, rust/tokenmania/.devcontainer/devcontainer.json, rust/who_am_i/.devcontainer/devcontainer.json
- downgrade docker image using dfx version 0.25.0 instead of 0.27.0 for performance reasons on Apple Silicon
=> fix: Downgrade docker image to older dfx version

hosting/my_crypto_blog/BUILD.md, hosting/react/BUILD.md, motoko/backend_only/BUILD.md, motoko/daily_planner/BUILD.md, motoko/evm_block_explorer/BUILD.md, motoko/filevault/BUILD.md, motoko/flying_ninja/BUILD.md, motoko/hello_world/BUILD.md, motoko/llm_chatbot/BUILD.md, motoko/tokenmania/BUILD.md, motoko/who_am_i/BUILD.md, rust/backend_only/BUILD.md, rust/backend_wasm64/BUILD.md, rust/daily_planner/BUILD.md, rust/evm_block_explorer/BUILD.md, rust/flying_ninja/BUILD.md, rust/hello_world/BUILD.md, rust/llm_chatbot/BUILD.md, rust/tokenmania/BUILD.md, rust/who_am_i/BUILD.md
=> update: ICP Ninja BUILD.md

rust/who_am_i/README.md
=> Standardize README

rust/hello_world/README.md
=> standardize README 

rust/inter-canister-calls/README.md
=> fix: format

rust/send_http_post/README.md
=> add: Deploy to ICP + standardize README

hosting/my_crypto_blog/BUILD.md, hosting/react/BUILD.md, motoko/backend_only/BUILD.md, motoko/daily_planner/BUILD.md, motoko/evm_block_explorer/BUILD.md, motoko/filevault/BUILD.md, motoko/flying_ninja/BUILD.md, motoko/hello_world/BUILD.md, motoko/llm_chatbot/BUILD.md, motoko/tokenmania/BUILD.md, motoko/who_am_i/BUILD.md, rust/backend_only/BUILD.md, rust/backend_wasm64/BUILD.md, rust/daily_planner/BUILD.md, rust/evm_block_explorer/BUILD.md, rust/flying_ninja/BUILD.md, rust/hello_world/BUILD.md, rust/llm_chatbot/BUILD.md, rust/tokenmania/BUILD.md, rust/who_am_i/BUILD.md
=> fix: Numbering in BUILD.md file

hosting/my_crypto_blog/README.md, hosting/react/README.md, motoko/backend_only/README.md, motoko/evm_block_explorer/README.md, motoko/filevault/README.md, motoko/hello_world/README.md, motoko/llm_chatbot/README.md, motoko/tokenmania/README.md, motoko/who_am_i/README.md, rust/backend_only/README.md, rust/backend_wasm64/README.md, rust/daily_planner/README.md, rust/evm_block_explorer/README.md, rust/flying_ninja/README.md, rust/hello_world/README.md, rust/llm_chatbot/README.md, rust/tokenmania/README.md
Updating readmes for ninja examples
=> Update Deploy to Run

rust/basic_bitcoin/README.md
Made some minor changes to the README to ensure the ToC was up to date, correctly linking to the ICP Ninja section, etc.
=> basic_bitcoin: Update TOC of Readme

NINJA_CONTRIBUTING.md
- mention prebuild step to install packages
=> chore: Update NINJA_CONTRIBUTING.md

motoko/nft-creator/backend/app.mo, motoko/nft-creator/mops.toml
=> add missing dependencies

motoko/vetkeys/README.md, rust/vetkeys/README.md
=> Add links to vetkeys examples

.github/CODEOWNERS, .github/workflows/motoko-canister-factory-example.yml, motoko/canister_factory/README.md, motoko/canister_factory/demo.sh, motoko/canister_factory/dfx.json, motoko/canister_factory/mops.toml, motoko/canister_factory/src/backend/AnotherChild.mo, motoko/canister_factory/src/backend/Child.mo, motoko/canister_factory/src/backend/Main.mo
=> add example

rust/unit_testable_rust_canister/src/hello_canister/Cargo.toml, rust/unit_testable_rust_canister/src/hello_canister/hello_canister.did, rust/unit_testable_rust_canister/src/hello_canister/src/canister_api.rs, rust/unit_testable_rust_canister/src/hello_canister/src/lib.rs, rust/unit_testable_rust_canister/src/hello_canister/src/types/mod.rs, rust/unit_testable_rust_canister/src/hello_canister/tests/integration_tests.rs
**Overview**
Add a test to show how to test for candid compatibility, and also fix the candid so it matches implementation in the example.
It runs in ICP Ninja.
=> fix: Fix example so candid matches canister implementation

rust/unit_testable_rust_canister/Cargo.lock
This updates the lockfile that was preventing the example from running on icp-ninja.
=> fix: Fix lockfile
