dfinity/examples

motoko/hello-world/src/main.mo
motoko/phone-book/src/phonebook/main.mo
motoko/phone-book/src/phonebook/public/index.jsx
motoko/pubsub/dfx.json
motoko/pubsub/src/pub/main.mo

**Overview**
This allows someone to use `dfx` at version 0.5.7, where the `stdlib` was renamed to `base` and the namespaces are now Title Case.
It's better to have demos working with the latest `dfx` sdk version.
If people attempt to run the examples with a previous version of `dfx`, the canisters would not build.

Update to 0.5.7

---

motoko/favorite_cities/README.md

**Overview**
README says to use favorite-cities when the canister is named favorite_cities
Follow the README.
Fix the typo.
Rename the container reference typo in the README from favorite-cities to favorite_cities
No impact.

Fixing issue #33, swap favorite-cities with favorite_cities

---

motoko/calc/dfx.json

**Overview**
The calc example references dfx 0.5.2. Trying to follow the README with the latest SDK 0.5.7 installed results in an error
Update the dfx.json to 0.5.7 to reflect the latest version of the SDK.
Discovering how to forcefully install the older 0.5.2 SDK version.
Updating the dfx.json version to 0.5.7
Update the dfx.json version to 0.5.7
No impact.

Update dfx version from 0.5.2 to 0.5.7 for issue #35

---

motoko/phone-book/README.md

**Overview**
The README.md in the motoko phone-book example is the boilerplate from a `dfx new` and does not properly explain how to install or use the example application.
Update the README.md to accurately reflect the motoko phone-book example.
This might be an attempt to throw the user into the deep end without instruction, but that doesn't sync well with the purpose of this examples repo.
As a developer trying to understand this example, I ran into the problem where the Phone Number needed to be a Nat number and not a string. Using an E.164 phone number with the +1 prefix failed silently in the web interface. Initially I thought the example was a busted one, as the README was also the boilerplate from a `dfx new`. …

Update motoko phone-book README.md

---

motoko/calc/README.md
motoko/counter/README.md
motoko/echo/README.md
motoko/factorial/README.md
motoko/favorite_cities/README.md
motoko/hello-world/README.md
motoko/phone-book/README.md
motoko/pubsub/README.md
motoko/simple_to_do/README.md

**Overview**
Getting started isn't a section anymore. Update the link in all of the examples.

Update the link to the quick start download and install section

---

.github/workflows/provision-darwin.sh
.github/workflows/provision-linux.sh
motoko/calc/dfx.json
motoko/counter/dfx.json
motoko/echo/dfx.json
motoko/factorial/dfx.json
motoko/hello-world/dfx.json
motoko/hello_cycles/Makefile
motoko/hello_cycles/dfx.json
motoko/life/dfx.json
motoko/life/package-lock.json
motoko/life/package.json
motoko/phone-book/dfx.json
motoko/phone-book/package-lock.json
motoko/phone-book/package.json
motoko/pub-sub/dfx.json
motoko/quicksort/dfx.json
motoko/simple-to-do/dfx.json
motoko/superheroes/dfx.json
motoko/superheroes/package-lock.json
motoko/superheroes/package.json
motoko/whoami/dfx.json

Update all (motoko) samples to work with dfx 0.7.0-beta.5
- bump dfx in dfx.json and agent-js in packages.json
- npm update where necessary
- add superheroes/package-lock.json (other package-lock files are checked in, so I guess this one should be too)
- adjust hello_cycles Makefile test target since we now go to 11T cycles on install

update to 0.7.0-beta.5

---

motoko/encrypted-notes-dapp/src/frontend/src/components/Disclaimer.svelte
motoko/encrypted-notes-dapp/src/frontend/src/components/DisclaimerCopy.svelte
motoko/encrypted-notes-dapp/src/frontend/src/components/Hero.svelte
motoko/encrypted-notes-dapp/src/frontend/src/components/SidebarLayout.svelte

Implementing the request to add the following disclaimer to both before and after the user logs in.
> This sample dapp is intended exclusively for experimental purpose. The backend canister may be removed or reinstalled at any time without prior notice. You are advised not to use this dapp for storing your critical data such as keys or passwords.

Add disclaimer

---

motoko/encrypted-notes-dapp/package-lock.json
motoko/encrypted-notes-dapp/src/encrypted_notes_motoko/main.mo

- Replace array for notesByUser with list to get rid of warning about append performance and adjust all comments
- Remove functions that are now part of the library (Principal.isAnonymous) 
- Remove hack for array private type

Cleanup encrypted notes sample dapp motoko canister

---

motoko/encrypted-notes-dapp/Dockerfile
motoko/encrypted-notes-dapp/README.md

* Upgrade DFX version to 0.9.3
* Use `sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"` instead of `sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"`
* Add `libdigest-sha-perl` dependency (since DFX now requires `shasum`)
* Improve README.md

Fixed Docker deployment for encrypted_notes_dapp

---

motoko/defi/README.md
motoko/defi/dfx.json
motoko/defi/src/defi_dapp/exchange.mo
motoko/defi/src/defi_dapp/main.mo
motoko/defi/src/frontend/package-lock.json
motoko/defi/src/frontend/package.json

**Overview**
This PR fixes a bug in the Motoko implementation of the defi_dapp: the profix from executing a swap of tokens between two principals should be accounted to the dapp's principal rather than the ledger.
In addition, this PR bumps up the dfx version and dependencies.

fix defi_dapp/exchange.mo

---

svelte-motoko-starter/src/frontend/package-lock.json
svelte-motoko-starter/src/frontend/package.json
svelte-motoko-starter/src/frontend/public/index.html
svelte-motoko-starter/src/frontend/rollup.config.js

**Overview**
Resolves #249
- inject `"undefined"` values as default values for the canister ID to replace `process.env` in any case - better render an application with hints to the user in case II or the backend canisters have not been deployed rather than not catching error "process is not defined"
- move rollup replacer as last script
- fix svelte build with pre-processor for svelte templates 
- generate source map only in development
- ditech `iife` for modern es modules bundle

fix: svelte motoko starter build

---

motoko/dip-721-nft-container/src/Main.mo

**Overview**
I suspect a problem in the array access of this Motoko dip-721-nft-container example with ```List.get``` used.
My front-end was giving the wrong owner to a specific token id ( first of the list instead of the last ).
Token ownership was fix after this change.
Retrieve the right item using explicit to token id match.
Retrieve the right item using explicit to token id match.
I do not know the performance issue of this fix using ```List.find``` instead of .```List.get```

Motoko dip-721-nft-container example : wrong array list order access ?

---

rust/basic_bitcoin/Cargo.lock
rust/basic_bitcoin/dfx.json
rust/basic_bitcoin/src/basic_bitcoin/Cargo.toml
rust/basic_bitcoin/src/basic_bitcoin/src/bitcoin_wallet.rs

The PR bumps the bitcoin version to 0.28.1.
This version is better suited for follow-up development work.
In addition, there is a minor change: The version in the transaction is changed from 2 to 1, which is the commonly used version number.

Bump the bitcoin version to 0.28.1

---

motoko/classes/Makefile
motoko/classes/dfx.json
motoko/classes/src/test/Test.mo

* Change canister name to suit playground naming convention
* Reduce test iterations, so that we can generate profiling graph

change parameters on the classes example to better suit playground

---

motoko/basic_bitcoin/src/basic_bitcoin/src/BitcoinWallet.mo
rust/basic_bitcoin/src/basic_bitcoin/src/bitcoin_wallet.rs

Bug: It is possible that the current mock signer creates a mock signature that results in a transaction that is 1 byte smaller than the transactions signed with the proper ECDSA signing mechanism.
As a result, if we specify a low fee such as 1 sat/b, the current code sets the fee to `b-1` sat for a transaction of size `b` bytes, which causes the transaction to be rejected.
This PR fixes this problem by returning a mock signature with all bits set, both for the Rust and the Motoko version of the basic Bitcoin dapp.

Fixing bug in mock signer

---

motoko/encrypted-notes-dapp/README.md

Add security considerations for encrypted notes, linking to security best practices. 
This is the first in a series of PRs that adds links to security best practices to example dapps.

Add security considerations for encrypted notes

---

motoko/actor_reference/README.md

This adds a reference to the security best practices for the Actor Reference example. The example does not really have a strong relation to security concerns, but a general reference still makes sense IMO.

Add security considerations for Actor Reference example

---

motoko/factorial/README.md
motoko/hello/README.md
rust/hello/README.md

Add security best practices link to docs for factorial and hello examples. 
Since the examples are almost trivial this is just a link to the best practices without listing specific examples relevant for these apps.

Add security best practices link to docs for factorial and hello examples

---

motoko/minimal-counter-dapp/README.md
motoko/persistent-storage/README.md
motoko/phone-book/README.md
motoko/pub-sub/README.md
rust/pub-sub/README.md

Add security best practices link to docs for counter, phone-book, and pub-sub examples

Add security best practices link to docs for counter, phone-book, and pub-sub examples

---

motoko/threshold-ecdsa/src/ecdsa_example_motoko/main.mo
rust/threshold-ecdsa/src/ecdsa_example_rust/src/lib.rs

**Overview**
The number of cycles attached to signing cals in the threshold ECDSA examples is not sufficient. The current amount of cycles sent is `10_000_000_000`, however the number of cycles needs to be higher than `21_538_461_538`
NA
NA
Increase the number of cycles attached to sign request.
NA

Fix number of cycles sent to sign in threshold ECDSA examples

---

motoko/defi/scripts/install.sh
rust/nft-wallet/README.md
rust/nft-wallet/start.sh
svelte/svelte-motoko-starter/README.md

**Overview**
As reported on [this forum post](https://forum.dfinity.org/t/error-when-deploying-svelte-examples-from-dfinity-samples-bank/16983/22), installation instructions for II are outdated in the examples.

fix outdated II installation instructions

---

motoko/basic_bitcoin/dfx.json
rust/basic_bitcoin/dfx.json

**Overview**
dfx.json says that bitcoin is enabled for the BTC examples, but this setting won't trigger if there is no project-specific network defined

add project-specific network to btc examples

---

motoko/exchange_rate/cleanup.sh
motoko/exchange_rate/package-lock.json
motoko/exchange_rate/package.json
rust/exchange_rate/package.json
rust/exchange_rate/src/declarations/exchange_rate_assets/exchange_rate_assets.did
rust/exchange_rate/src/declarations/exchange_rate_assets/exchange_rate_assets.did.d.ts
rust/exchange_rate/src/declarations/exchange_rate_assets/exchange_rate_assets.did.js
rust/exchange_rate/src/declarations/exchange_rate_assets/index.d.ts
rust/exchange_rate/src/declarations/exchange_rate_assets/index.js

`"prestart": "dfx generate exchange_rate"` Only works if canister already exists. If we check-in the declarations for both examples it is easier to deploy.

checkin declarations

---

motoko/ios-notifications/dapp-demo/src/www/src/auth.ts
motoko/ios-notifications/ios-dapp-demo/DAppExample/LoginSession.swift

**Overview**
Update example ios notifications app to use fragment for the delegation callback.

Use fragment for delegation callback

---

svelte/svelte-motoko-starter/README.md

Fix the path to copy the svelte-motoko-starter repo

fix: path in svelte-motoko-starter

---

rust/counter/README.md
svelte/svelte-motoko-starter/README.md

Change 'Mokoto' to 'Motoko' in example documentation. 
I'm assuming that was a typo.

Change 'Mokoto' to 'Motoko' in example documentation. 

---

.github/workflows/hosting-photo-storage-example.yml

I got this error:
```
[Invalid workflow file: .github/workflows/hosting-photo-storage-example.yml#L21](https://github.com/dfinity/examples/actions/runs/3958056577/workflow)
You have an error in your yaml syntax on line 21
```
Yaml verifiers say the problem is with the CLI lines that are not aligned (and start with `#`).
> All mapping items must start at the same column at line 25, column 1
> Implicit keys need to be on a single line at line 26, column 11
> Implicit map keys need to be followed by map values at line 26, column 11
> All mapping items must start at the same column at line 41, column 1
> Implicit keys need to be on a single line at line 42, column 11
> Implicit map keys need to be followed by map values at line 42, column 11

fix `run:` CLI comments in GH workflow for `hosting-photo-storage-example`

---

rust/basic_bitcoin/dfx.json
rust/basic_bitcoin/src/basic_bitcoin/build.sh

Prior to this commit, deploying the rust `basic_bitcoin` example failed with:
```
The replica returned an HTTP Error: Http Error: status 413 Payload Too Large, content type "application/cbor", content: Request 0x6a3ef24c0be4f7d988c107bcca95066d87e63f280ed38e0fe55976c444bc08d6 is too large. Message byte size 2841795 is larger than the max allowed 2097152.
Time: 0h:00m:19s
```
The binary is now gzipped, reducing its size to be below the limit.
Closes EXC-1329

fix: EXC-1329 the `basic_bitcoin` wasm is too large.

---

.github/workflows/rust-basic-bitcoin-example.yml
rust/basic_bitcoin/Makefile

Problem:
The CI only tested that `basic_bitcoin` compiles successfully, but didn't verify that the wasm can be deployed successfully. This resulted in bugs like #435 from slipping through the cracks.
Solution:
Harden CI to test that deploying the `basic_bitcoin` example.

fix: CI now tests deployment of the Rust basic_bitcoin example.

---

motoko/defi/src/frontend/rollup.config.js
motoko/encrypted-notes-dapp/rollup.config.js
motoko/exchange_rate/rollup.config.js
rust/defi/src/frontend/rollup.config.js
rust/exchange_rate/rollup.config.js
rust/nft-wallet/frontend/rollup.config.js
svelte/svelte-motoko-starter/src/frontend/rollup.config.js

**Overview**
The current build `dir` strategy shows a blank page on local deployments. This strategy is more how it used to be, with the addition of the `inlineDynamicImports` flag

fix: sets all rollup configs to use bundled json in iife format

---

rust/exchange_rate/src/main.rs

The MR fixes a problem with the current dapp. The intent of the transform function is to strip data from the original response so less data is added to the block. The current implementation does the opposite - adding data.
Manually inspected the change given the frontend is now working.

Use the transform to strip data instead of adding data

---

motoko/threshold-ecdsa/README.md
motoko/threshold-ecdsa/src/ecdsa_example_motoko/main.mo
motoko/threshold-ecdsa/src/ecdsa_example_motoko/utils/Hex.mo
motoko/threshold-ecdsa/src/ecdsa_example_motoko/utils/SHA256.mo
motoko/threshold-ecdsa/test.sh

Update the Motoko threshold-ecdsa example as follows:
* Use hex encoding (instead of candid blobs) as input and output representation for all types except the message
* Take the message in sign in raw form and hash it directly in the canister (instead of outside)
* Adapt the test.sh-script accordingly
* Adapt the README accordingly

Update Motoko threshold-ecdsa example

---

rust/basic_bitcoin/dfx.json
rust/basic_bitcoin/src/basic_bitcoin/build.sh

This PR adds a metadata section containing the candid service definition to the Rust basic bitcoin example. This is needed to ensure that we can retrieve the candid UI of the canister as described in the [documentation](https://internetcomputer.org/docs/current/samples/deploying-your-first-bitcoin-dapp).

fix: Add metadata section to Rust basic bitcoin example

---

rust/nft-wallet/deploy.sh
rust/nft-wallet/dfx.json
rust/nft-wallet/frontend/src/components/Authenticator.svelte
rust/nft-wallet/rust-toolchain.toml

**Overview**
I request this PR to fix #484 issue. (This `rust/nft-wallet` is related to #214 )
```bash
cd rust/nft-wallet
sh start.sh
check <nftwallet canister id>.localhost:8000
```

fix: rust/nft-wallet tutorial does not work properly

---

motoko/defi/dfx.json
motoko/internet_identity_integration/README.md
motoko/internet_identity_integration/dfx.json
motoko/ios-notifications/dapp-demo/dfx.json
rust/defi/dfx.json
rust/nft-wallet/dfx.json

With the switch from `ic-cdk-optimizer` to `ic-wasm` in the II build process, the uncompressed wasm will be too large for direct deployment with dfx. This PR therefore changes all references to the gzipped version of the asset.

chore: Switch to gzipped II dev build

---

rust/basic_bitcoin/README.md

Update the readme to use the lower case variant for the network to connect after the update on dependencies.

Update readme for rust basic bitcoin

---

hosting/static-website/README.md
hosting/unity-webgl-template/README.md
motoko/defi/src/defi_dapp/main.mo
motoko/defi/src/frontend/src/App.svelte
motoko/defi/src/frontend/src/components/Links.svelte
motoko/dip721-nft-container/README.md
motoko/encrypted-notes-dapp/Dockerfile
motoko/encrypted-notes-dapp/README.md
motoko/encrypted-notes-dapp/src/encrypted_notes_motoko/main.mo
motoko/encrypted-notes-dapp/src/encrypted_notes_rust/src/lib.rs
motoko/invoice-canister/candid/nns-cycles-minting.did
react-native-starter/src/App.tsx
rust/dip721-nft-container/README.md
rust/encrypted-notes-dapp/README.md
rust/tokens_transfer/src/lib.rs
svelte/svelte-motoko-starter/README.md
svelte/svelte-motoko-starter/src/frontend/src/components/Links.svelte
svelte/svelte-starter/README.md
svelte/svelte-starter/src/frontend/src/components/Links.svelte
svelte/sveltekit-starter/README.md

**Overview**
(second attempt after [pull/511](https://github.com/dfinity/examples/pull/511)) 
Fix broken URLs pointing to smartcontracts.org.
New documentation pages from https://internetcomputer.org/docs/current/ are now linked instead.
For each broken URL or unreachable page, an archive copy was checked to see which current document fits that link the best.
Links to old documentation pages should be replaced with the most appropriate current document.
N/A
N/A
N/A

Fix and review outdated documentation URLs from smartcontracts.org

---

.github/workflows/motoko-basic-bitcoin.yaml
motoko/basic_bitcoin/dfx.json
motoko/basic_bitcoin/src/basic_bitcoin/basic_bitcoin.did
motoko/basic_bitcoin/src/basic_bitcoin/src/BitcoinWallet.mo
motoko/basic_bitcoin/src/basic_bitcoin/src/Main.mo
motoko/basic_bitcoin/src/basic_bitcoin/src/Types.mo

* Update dfx.json to set the Bitcoin flag to true
* Switch casing of the network from camel case to snake case, which is more in line with the specification.

fix: Motoko Bitcoin example

---

.github/workflows/motoko-vetkd-example.yml
.github/workflows/provision-darwin.sh
.github/workflows/rust-vetkd-example.yml
motoko/vetkd/dfx.json
motoko/vetkd/package-lock.json
motoko/vetkd/package.json
motoko/vetkd/src/app_backend/Main.mo
motoko/vetkd/src/app_frontend_js/assets/main.css
motoko/vetkd/src/app_frontend_js/src/index.html
motoko/vetkd/src/app_frontend_js/src/index.js
rust/vetkd/dfx.json
rust/vetkd/package-lock.json
rust/vetkd/package.json
rust/vetkd/src/app_backend/src/lib.rs
rust/vetkd/src/app_frontend_js/assets/main.css
rust/vetkd/src/app_frontend_js/src/index.html
rust/vetkd/src/app_frontend_js/src/index.js

Extends the vetKD IBE demos (both Rust and Motoko) with Internet Identity login and allows to IBE-encrypt for a particular principal.
Also updates `.github/workflows/provision-darwin.sh` to make the installed node-js version configurable via an environment variable (leaving the default unchanged). This is done so that the CI runs for the vetkd Rust and motoko examples for macOS/darwin can use a newer node-js version (here 19.8.1) because with the old version (14.15.4) webpack fails with the error message "Field 'browser' doesn't contain a valid alias configuration" for the `@dfinity/identity` dependency of the `@dfinity/auth-client`.

Extend vetKD IBE demo with Internet Identity login

---

motoko/encrypted-notes-dapp-vetkd/README.md
motoko/encrypted-notes-dapp/README.md

The README of the encrypted-notes-dapp-vetkd was misleading for the case where user wants to use the Rust deployment. In particular, users might think that if they want to use the Rust deployment, they simply don't have to call `export BUILD_ENV=motoko`, while in fact they have to call `export BUILD_ENV=rust` instead. This PR adapts the documentation to clarify that.
The PR also fixes wrong instructions for the encrypted-notes-dapp. The README wrongly says to navigate to `examples/rust/encrypted-notes-dapp`, but this folder only contains a README and no code (because the deployment is selected via an environment variable).

Improve documentation for encrypted notes examples

---

rust/basic_bitcoin/src/basic_bitcoin/src/bitcoin_wallet.rs

This simple PR makes the code where the P2PKH Bitcoin address is derived from the public key a bit nicer in that it now uses a dedicated function for both SHA-256 and RIPEMD-160.

Polishing the hashing part when generating a P2PKH address

---

motoko/basic_bitcoin/src/basic_bitcoin/basic_bitcoin.did
motoko/basic_bitcoin/src/basic_bitcoin/src/BitcoinApi.mo
motoko/basic_bitcoin/src/basic_bitcoin/src/BitcoinWallet.mo
motoko/basic_bitcoin/src/basic_bitcoin/src/EcdsaApi.mo
motoko/basic_bitcoin/src/basic_bitcoin/src/Main.mo
motoko/basic_bitcoin/src/basic_bitcoin/src/Types.mo
rust/basic_bitcoin/src/basic_bitcoin/basic_bitcoin.did
rust/basic_bitcoin/src/basic_bitcoin/src/bitcoin_api.rs
rust/basic_bitcoin/src/basic_bitcoin/src/bitcoin_wallet.rs
rust/basic_bitcoin/src/basic_bitcoin/src/ecdsa_api.rs

The PR polishes and fixes a few minor things in the basic Bitcoin example:
- Renamed variables to indicate that fees are measured in sat/vbyte (and not sat/byte).
- Introduced a `transaction_id` type as the return value for the `send` function.
- Introduced the `SIGN_WITH_ECDSA_COST_CYCLES` constant.
- Fixed the index for the median fee (the median fee is at index 50 and not 49).
- Reshuffled some comments and code.

Polishing the basic Bitcoin example

---

.github/workflows/motoko-encrypted-notes-vetkd-example.yml
.github/workflows/motoko-encrypted-notes-vetkd-skip.yml
.github/workflows/rust-encrypted-notes-vetkd-example.yml
.github/workflows/rust-encrypted-notes-vetkd-skip.yml
motoko/encrypted-notes-dapp-vetkd/Cargo.lock
motoko/encrypted-notes-dapp-vetkd/Makefile
motoko/encrypted-notes-dapp-vetkd/README.md
motoko/encrypted-notes-dapp-vetkd/package-lock.json
motoko/encrypted-notes-dapp-vetkd/package.json
motoko/encrypted-notes-dapp-vetkd/pre_deploy.sh
motoko/encrypted-notes-dapp-vetkd/src/encrypted_notes_motoko/main.mo
motoko/encrypted-notes-dapp-vetkd/src/encrypted_notes_rust/Cargo.toml
motoko/encrypted-notes-dapp-vetkd/src/encrypted_notes_rust/src/encrypted_notes_rust.did
motoko/encrypted-notes-dapp-vetkd/src/encrypted_notes_rust/src/lib.rs
motoko/encrypted-notes-dapp-vetkd/src/encrypted_notes_rust/src/vetkd_types.rs
motoko/encrypted-notes-dapp-vetkd/src/frontend/src/components/EditNote.svelte
motoko/encrypted-notes-dapp-vetkd/src/frontend/src/components/NewNote.svelte
motoko/encrypted-notes-dapp-vetkd/src/frontend/src/components/SharingEditor.svelte
motoko/encrypted-notes-dapp-vetkd/src/frontend/src/components/SidebarLayout.svelte
motoko/encrypted-notes-dapp-vetkd/src/frontend/src/lib/crypto.ts
motoko/encrypted-notes-dapp-vetkd/src/frontend/src/lib/note.ts
motoko/encrypted-notes-dapp-vetkd/src/frontend/src/store/auth.ts
motoko/encrypted-notes-dapp-vetkd/src/frontend/src/store/notes.ts
motoko/encrypted-notes-dapp-vetkd/src/frontend/src/store/notifications.ts
motoko/encrypted-notes-dapp-vetkd/test_whoami.sh

Enables sharing of notes in the vetKD-variant of the encrypted notes dapp. To do this, the backend is entirely restructured so that notes are stored by their ID and vetKeys are derived using the note ID (and the note owner) as derivation ID.

Enable sharing of notes in vetKD encrypted notes

---

.github/workflows/motoko-internet-identity-integration-example.yaml
motoko/internet_identity_integration/README.md
motoko/internet_identity_integration/webpack.config.js

Due to II now having multiple JS bundles, using query parameter based routing no longer works in Chrome and FF. To alleviate this we recommend using Chrome or FF and to use the localhost subdomain approach.

Update II integration example to work with Chrome and FF again

---

rust/pub-sub/README.md

The list of Steps in the pub-sub project's readme.md file has some errors.
It looks like the code was updated and the readme.md became out-of-date. 
This PR corrects the steps so that the example code can be used as intended.

Fix instructional steps in pub-sub readme.md

---

.github/workflows/motoko-defi-example.yml
.github/workflows/rust-defi-example.yml

CI was broken for motoko and rust defi examples because the `dfx` version used could not handle the gzipped II canister.

Use dfx with gzip support for defi examples

---

.github/workflows/rust-encrypted-notes-example.yml

Fix CI for rust-encrypted-notes example dapp. It was broken because the dfx version used could not handle the gzipped II canister.

fix: use dfx with gzip support for rust-encrypted-notes example

---

.github/workflows/motoko-counter-example.yaml

The dorny/paths-filter GH action needs a checkout for `push` events.
Also updated the conditionals on the tests to follow previous behavior:
- on push to master, run all tests
- on pull requests, run only changed tests

fix: dorny/path-filter requires checkout for pushes

---

README.md
motoko/actor_reference/README.md
motoko/basic_bitcoin/README.md
motoko/basic_dao/README.md
motoko/classes/README.md
motoko/defi/README.md
motoko/echo/README.md
motoko/encrypted-notes-dapp/README.md
motoko/hello/README.md
motoko/http_counter/README.md
motoko/internet_identity_integration/README.md
motoko/invoice-canister/docs/bounty-task-checklist.md
motoko/life/README.md
motoko/phone-book/README.md
motoko/random_maze/README.md
motoko/superheroes/README.md
motoko/threshold-ecdsa/README.md
rust/basic_bitcoin/README.md
rust/basic_dao/README.md
rust/counter/README.md
rust/encrypted-notes-dapp/README.md
rust/hello/README.md
rust/threshold-ecdsa/README.md
svelte/README.md
svelte/svelte-motoko-starter/README.md
svelte/svelte-starter/README.md
svelte/sveltekit-starter/README.md

Removes broken links and images from README files so that they render as submodules on the dev docs correctly.

Remove broken links & images

---

.github/workflows/motoko-encrypted-notes-vetkd-example.yml
.github/workflows/rust-encrypted-notes-vetkd-example.yml

Removes the custom DFX versions used for provisioning the Linux CI checks for the encrypted-notes-vetkd dapp for both Rust and Motoko. This is done because the custom DFX version, 0.14.2, is outdated. With this, the default DFX version defined in `provision-linux.sh` is used, which version is regularly updated to ensure the examples work with the latest version.

Use default provisioned DFX version in encrypted-notes-vetkd dapps

---

hosting/static-website/README.md
motoko/encrypted-notes-dapp/README.md
motoko/hello/README.md
motoko/internet_identity_integration/README.md
motoko/minimal-counter-dapp/README.md
rust/encrypted-notes-dapp/README.md
rust/hello/README.md

To upgrade the portal from Docusaurus v2 to v3, we need to ensure all markdown content can be rendered with the v3 mdx parser.
See https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3#preparing-content-for-mdx-v3 for more

chore: update markdown content to comply with mdx v3 parsing rules

---

motoko/icp_transfer/demo.sh
motoko/token_transfer/demo.sh
rust/icp_transfer/demo.sh
rust/token_transfer/demo.sh

**Overview**
this way the `demo.sh` doesn't fail if the identity already exist and can be executed locally as well.

🩹 forcing identity creation

---

motoko/basic_bitcoin/README.md

lower case testnet in the argument to properly deploy
**Overview**
Must lower case `testnet` argument to properly deploy Bitcoin canister

fix: testnet capitalization

---

.github/workflows/update-ic-commit.yml

The workflow was missing setting the github output which was checked by a different workflow step in order to raise a PR

chore: add step to trigger PR in workflow

---

motoko/random_maze/src/random_maze/Main.mo

Fix broken implementation of `chooseMax` (courtesy of Timo Hanke)

bugfix: motoko random maze example

---

.github/CODEOWNERS
.github/workflows/motoko-canister-logs-example.yml
.github/workflows/rust-canister-logs-example.yml
motoko/canister_logs/Makefile
motoko/canister_logs/README.md
motoko/counter/README.md
rust/canister_logs/Makefile
rust/canister_logs/README.md

This PR fixes ownership, readme nits and workflow for canister_logs examples.

chore: fix CODEOWNERS and workflow for canister-logs example

---

.github/CODEOWNERS

Changes the ownership of vetKD examples from the crypto division (div-Crypto) to the crypto libraries team (dept-crypto-library).

Make crypto-library team own vetKD examples

---

.github/CODEOWNERS

Adapts the CODEOWERS file so that the Crypto team (rather than the Crypto division) owns all encrypted-notes (incl. encrypted-notes-vetkd) and threshold-ecdsa dapps, i.e., for both Rust and Motoko. So far, /rust/threshold-ecdsa/ was owned by the Consensus team, while /motoko/threshold-ecdsa/ was owned by the Crypto team.

Make Crypto team own all encrypted-notes and threshold-ecdsa dapps

---

.github/CODEOWNERS

Adapts the CODEOWERS file so that the Crypto team, rather than the Crypto division, owns the Motoko threshold-ecdsa example dapp. The idea was to do this already in https://github.com/dfinity/examples/pull/880, but that was missed.

Make Crypto team own the Motoko threshold-ecdsa dapp

---

.github/workflows/close-stale-issues.yaml

Use the `actions/stale` [workflow](https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues) to automatically close stale issues

chore: add workflow to close stale issues

---

rust/image-classification/Cargo.lock
rust/image-classification/README.md
rust/image-classification/dfx.json
rust/image-classification/src/backend/Cargo.toml
rust/image-classification/src/backend/backend.did
rust/image-classification/src/backend/src/lib.rs
rust/image-classification/src/declarations/backend/backend.did
rust/image-classification/src/declarations/backend/backend.did.d.ts
rust/image-classification/src/declarations/backend/backend.did.js
rust/image-classification/src/frontend/assets/main.css
rust/image-classification/src/frontend/src/index.html
rust/image-classification/src/frontend/src/index.js

The mainnet and dfx version 0.20.2-beta.0 support Wasm SIMD. Sonos Tract also supports Wasm SIMD on `master`.
This PR updates the Sonos Tract dependency to the version that supports Wasm SIMD.
Now image classification can run in a query. The example is modified to add an option for running as a query or update.

Use Wasm SIMD in the image classification example

---

rust/basic_bitcoin/src/basic_bitcoin/src/bitcoin_api.rs
rust/basic_bitcoin/src/basic_bitcoin/src/bitcoin_wallet.rs
rust/basic_bitcoin/src/basic_bitcoin/src/ecdsa_api.rs

The IC CDK offers dedicated functions for threshold ECDSA and the Bitcoin integration, which are currently not used in the `basic_bitcoin` sample project.
This PR changes this, which makes the codebase slightly smaller and easier to use.

chore: Use ECDSA and Bitcoin IC CDK Functionality

---

motoko/auth_client_demo/README.md
motoko/auth_client_demo/deps/candid/rdmx6-jaaaa-aaaaa-aaadq-cai.did
motoko/auth_client_demo/deps/pulled.json
motoko/auth_client_demo/dfx.json
motoko/auth_client_demo/package-lock.json
motoko/auth_client_demo/package.json
motoko/auth_client_demo/src/auth_client_demo_assets/react/index.jsx
motoko/auth_client_demo/src/auth_client_demo_assets/react/use-auth-client.jsx
motoko/auth_client_demo/src/auth_client_demo_assets/svelte/package-lock.json
motoko/auth_client_demo/src/auth_client_demo_assets/svelte/package.json
motoko/auth_client_demo/src/auth_client_demo_assets/svelte/src/stores/auth.js
motoko/auth_client_demo/src/auth_client_demo_assets/vanilla/index.ts
motoko/auth_client_demo/src/auth_client_demo_assets/vanilla/views/index.ts
motoko/auth_client_demo/src/auth_client_demo_assets/vue/store/auth.js

**Overview**
The current documented flow on [intern](https://internetcomputer.org/docs/current/references/samples/motoko/auth_client_demo/) fails. This updates the dependencies, fixes an issue with Internet Identity local builds, cleans up some inconsistencies among versions, and adds new documentation

feat: auth client demo safari compatibility

---

motoko/icp_transfer/README.md

Wrong command: `dfx dfx new --type=motoko icp_transfer --no-frontend` changed to 
`dfx new --type=motoko icp_transfer --no-frontend`

Fix broken command on icp_transfer

---

motoko/canister_logs/Makefile
motoko/canister_logs/src/Main.mo
rust/canister_logs/Makefile
rust/canister_logs/canister_logs.did
rust/canister_logs/src/lib.rs

This PR adds more cases to the canister logging examples in Rust and Motoko.
Specifically it adds a case of recording logs in a query method called in replicated mode.
It also adds separate tests for each canister logging example case.

chore: update canister_logs examples with replicated query cases

---

motoko/canister_logs/Makefile
motoko/canister_logs/src/Main.mo
rust/canister_logs/Makefile
rust/canister_logs/canister_logs.did
rust/canister_logs/src/lib.rs

This PR updates canister logging examples with trapped query calls in replicated and non-replicated modes.
It also improves tests' comments.

chore: update canister logging examples with trapped query calls

---

.github/workflows/motoko-threshold-schnorr-example.yaml
.github/workflows/rust-threshold-schnorr-example.yml
motoko/threshold-schnorr/Makefile
motoko/threshold-schnorr/README.md
motoko/threshold-schnorr/dfx.json
motoko/threshold-schnorr/src/schnorr_example_motoko/main.mo
motoko/threshold-schnorr/test.sh
rust/threshold-schnorr/Cargo.lock
rust/threshold-schnorr/Makefile
rust/threshold-schnorr/README.md
rust/threshold-schnorr/dfx.json
rust/threshold-schnorr/src/schnorr_example_rust/Cargo.toml
rust/threshold-schnorr/src/schnorr_example_rust/schnorr_example.did
rust/threshold-schnorr/src/schnorr_example_rust/src/wasm_only.rs
rust/threshold-schnorr/src/schnorr_example_rust/tests/tests.rs

The rust tests were disabled because PocketIC doesn't yet support Schnorr but will in the future. Having this example without a mock seems more important than having tests enabled for a few weeks, therefore, the tests are disabled until PocketIC supports Schnorr.

CRP-2532 remove mock API from Schnorr example since dfx now supports Schnorr

---

rust/basic_bitcoin/README.md
rust/basic_bitcoin/src/basic_bitcoin/basic_bitcoin.did
rust/basic_bitcoin/src/basic_bitcoin/src/bitcoin_api.rs
rust/basic_bitcoin/src/basic_bitcoin/src/lib.rs

A new endpoint is added to Bitcoin canister, this PR shows its desired usage.

chore: Add example of using bitcoin_get_block_headers to basic_bitcoin

---

rust/basic_bitcoin/README.md
rust/basic_bitcoin/dfx.json
rust/basic_bitcoin/src/basic_bitcoin/build.sh

**Overview**
Build script is outdated, this PR fixes the script to include candid in metadata properly.

chore: Fix broken build script for basic_bitcoin canister

---

.github/workflows/provision-pocket-ic-server.sh
motoko/parallel_calls/Cargo.lock
motoko/parallel_calls/multi_subnet/Cargo.toml
rust/guards/Cargo.lock
rust/guards/Cargo.toml
rust/parallel_calls/Cargo.lock
rust/parallel_calls/src/callee/Cargo.toml
rust/parallel_calls/src/caller/Cargo.toml
rust/parallel_calls/src/multi_subnet/Cargo.toml
rust/parallel_calls/src/parallel_calls_backend/Cargo.toml
rust/threshold-schnorr/Cargo.lock
rust/threshold-schnorr/src/schnorr_example_rust/Cargo.toml

**Overview**
`ic-cdk` versions `0.13` and `0.14` have been yanked.
Examples should not encourage users to use vulnerable versions of `ic-cdk`.
- Update `ic-cdk` version in all rust repositories.
- Update `ic-cdk` version in all rust repositories.
There will be fewer crates that use this as an example that are then vulnerable. :-)
By the way, I note that old `ic-cdk` is also used by `pocket-ic` v3, used here, but `pocket-ic` is used only in development so this is less of a concern.  Updating `pocket-ic` is much harder than just bumping a version number.

fix(rust): Update ic-cdk

---

rust/pub-sub/src/subscriber/src/subscriber.did

Counter and Subscriber are structs in Rust and therefore records in Candid. Variants are for Enums.
**Overview**
For correctness sake (esp. in beginner-friendly tutorials)
Nothing.
The correct types.
Changing the candid to the correct types.
Users will learn candid correctly.

Update subscriber.did with correct types

---

rust/basic_ethereum/basic_ethereum.did
rust/basic_ethereum/src/lib.rs
rust/basic_ethereum/src/state.rs

Since `Ankr` stopped working, the `basic_ethereum` example should use a different provider.
This PR `changes` the provider to `PublicNode`.
The PR further makes the `address` parameter of `get_balance` optional for the sake of consistency.

Switching from Ankr to PublicNode as the single EVM RPC service

---

motoko/vetkd/src/app_backend/Main.mo
motoko/vetkd/src/app_frontend_js/assets/.ic-assets.json5
motoko/vetkd/src/app_frontend_js/src/.ic-assets.json5
motoko/vetkd/src/app_frontend_js/src/index.js
rust/vetkd/src/app_frontend_js/assets/.ic-assets.json5
rust/vetkd/src/app_frontend_js/src/.ic-assets.json5
rust/vetkd/src/app_frontend_js/src/index.js

* Fixes the Internet Identity (II) integration in the vetKD examples by using the new environment variables for canister IDs (see [changelog of SDK 0.18](https://github.com/dfinity/sdk/blob/master/CHANGELOG.md#0180))
* Makes the example work in Safari by removing the `upgrade-insecure-requests;` content security policy (CSP) and by using `localhost` instead of `127.0.0.1` when calling II.

Fix Internet Identity integration in vetKD examples and make them work in Safari

---

motoko/send_http_get/src/send_http_get_backend/main.mo
rust/send_http_get/src/send_http_get_backend/src/lib.rs

The `api.pro.coinbase.com` has been deprecated and thus this PR replaces `api.pro.coinbase.com` by `api.exchange.coinbase.com` in canister http outcall examples.

fix: coinbase API

---

.github/workflows/rust-nft-wallet-example.yml

This PR fixes the dfx port from 8000 to 4943 in rust-nft-wallet tests.

fix: dfx port in rust-nft-wallet tests

---

rust/basic_bitcoin/dfx.json

`dfx start` didn't instantiate the bitcoin canister unless `--enable-bitcoin` was passed. The change in the config fixes this.
Closes CRP-2566.

fix bitcoin config in rust basic_bitcoin

---

rust/basic_bitcoin/src/basic_bitcoin/src/ecdsa_api.rs

**Overview**
The current process for retrieving a public key (via schnorr_public_key or ecdsa_public_key) takes approximately 9 seconds each time a user requests an address.  By storing public keys in a static variable, I want to improve performance and minimize cycle burn rate in the canister. It can serve as a good example for developers.
Public keys should be stored in a static variable, allowing retrieval without calling the key generation functions every time.
thread_local storage with static variables that do persist across calls, but not across updates. 
What …

feat(basic_bitcoin): cache ecdsa

---

motoko/basic_bitcoin/README.md

This example now also supports taproot.

update motoko basic_bitcoin readme

---

rust/basic_bitcoin/README.md

If `llvm` with `wasm32-unknown-unknown` is not installed, the compilation would error with something similar to
```
warning: error: unable to create target: 'No available targets are compatible with triple "wasm32-unknown-unknown"'
warning: 1 error generated.
warning: error: unable to create target: 'No available targets are compatible with triple "wasm32-unknown-unknown"'
warning: 1 error generated.
error: failed to run custom build command for `secp256k1-sys v0.9.2`
```
See https://github.com/rust-bitcoin/rust-bitcoin/issues/2331 for more details.

Add `llvm` with `wasm32-unknown-unknown` as requirement to rust basic bitcoin

---

rust/canister-snapshots/src/chat/src/lib.rs

This PR adds some small tweaks in the canister-snapshots example which would allow people to replicate what will be recorded for the Beryllium demo video.

chore: Updates to canister-snapshots example for beryllium demo

---

.github/workflows/rust-threshold-mock-example.yml
.github/workflows/rust-x509-example.yml

macos-12 runners have been deprecated and their CI jobs are [failing](https://github.com/dfinity/examples/actions/runs/11895652584/job/33147567361) by now

fix(ci): use macos-15 instead of deprecated macos-12

---

.github/workflows/update-ic-commit.yml

**Overview**
This is part of a larger effort to remove the need for PATs generated by service accounts and move them to GitHub apps.

chore(IDX): replace PAT with GitHub App

---

.github/workflows/rust-parallel-calls-example.yml
rust/parallel_calls/Cargo.lock
rust/parallel_calls/src/callee/Cargo.toml
rust/parallel_calls/src/caller/Cargo.toml
rust/parallel_calls/src/multi_subnet/Cargo.toml
rust/parallel_calls/src/multi_subnet/src/main.rs

The parallel calls Rust example demonstrate the performance difference between sequential and parallel calls using Pocket IC, but this hasn't been tested in CI so far (and in fact the example stopped working as expected after the cycles costs for inter-canister calls were increased).

chore: Add Pocket-IC tests to the parallel calls example CI

---

archive/motoko/hello/src/hello/main.mo
motoko/minimal-counter-dapp/package-lock.json
motoko/minimal-counter-dapp/src/minimal_dapp_backend/main.mo
motoko/minimal-counter-dapp/src/minimal_dapp_frontend/package.json
motoko/minimal-counter-dapp/src/minimal_dapp_frontend/vite.config.js
motoko/superheroes/src/superheroes/Main.mo

Also bump agent-js for counter app

Update Superheroes example to use ordered map

---

.github/CODEOWNERS

Transfer ownership of the `motoko/icrc2-swap` and `rust/defi` examples from `@dfinity/div-Crypto` to `@dfinity/growth` because the former team name is outdated.

Let growth team own motoko/icrc2-swap and rust/defi

---

.github/workflows/provision-linux.sh

This PR upgrades the node version to v22 in the `.github/workflows/provision-linux.sh` action. This resolves the CI issue for the `rust/parallel_calls` example. 
4/125 checks finished. The failing 4 are related to other issues, see for instance PR #1075.

Upgrade to Node 22

---

motoko/token_transfer/README.md
motoko/token_transfer_from/README.md
rust/icp_transfer/README.md
rust/token_transfer/README.md
rust/token_transfer_from/README.md

I recognized we introduced a link which doesn't work in this PR that got merged recently: https://github.com/dfinity/examples/pull/1073

fix link to download latest icrc1-ledger

---

motoko/token_transfer/README.md
motoko/token_transfer_from/README.md
rust/token_transfer/README.md
rust/token_transfer_from/README.md

The script that downloads the latest ICRC ledger `wasm` and `did` files was recently updated to download them using [the official ledger releases](https://github.com/dfinity/ic/releases?q=ledger-suite-icrc&expanded=false), rather than the latest commit on the `master` branch of the [ic](https://github.com/dfinity/ic) repository.
The links to the script in the documentation point to a specific commit in the `ic` repository. This PR proposes to update the links to the commit where the script was updated, so that users end up with an officially released ledger.

fix(ICRC_Ledger): FI-1654: Update link to script that downloads latest ICRC ledger

---

motoko/encrypted-notes-dapp-vetkd/README.md

The encrypted-notes-dapp-vetkd that lives in the motoko folder can do both Rust and Motoko. The README needs to reflect this, so this PR basically re-applies https://github.com/dfinity/examples/pull/617, which apparently accidentally got lost via https://github.com/dfinity/examples/pull/705.

Explain how to use Rust for encrypted-notes-dapp-vetkd in README

---

motoko/icrc2-swap/README.md

This PR adds a security disclaimer to the ICRC-2 swap example to highlight potential security risks in inter-canister calls. It also includes a link to the security best practices documentation, where these issues are explained in more detail.

Add security disclaimer in the icrc-2 swap example

---

rust/basic_bitcoin/src/basic_bitcoin/src/lib.rs

The key `dfx_test_key` should be used for local development of Bitcoin dapps using `regtest` mode. This was changed when working on threshold Schnorr. As Schnorr signatures are supported now, the key name can be reverted to `dfx_test_key`.

chore: Fixing the ECDSA test key name for local deployment of the basic Bitcoin dapp

---

.github/workflows/provision-darwin.sh
.github/workflows/provision-linux.sh
rust/parallel_calls/Cargo.lock
rust/parallel_calls/rust-toolchain.toml
rust/parallel_calls/src/multi_subnet/Cargo.toml
rust/parallel_calls/src/multi_subnet/src/main.rs

Updates to dfx 0.25.1.
Also updates rust/parallel-calls to pocket-ic 7.0.0, necessary as seen at https://github.com/dfinity/examples/actions/runs/13997604453/job/39196490571?pr=1113.

chore: update to dfx 0.25.1

---

svelte/svelte-motoko-starter/README.md
svelte/svelte-starter/README.md
svelte/sveltekit-starter/README.md
svelte/sveltekit-starter/package-lock.json
svelte/sveltekit-starter/package.json
svelte/sveltekit-starter/vite.config.ts

**Overview**
The default port is now 4943 - this PR updates the docs and scripts to use it.

chore: Remove reference to port :8000 from the svelte examples

---

motoko/llm_chatbot/frontend/src/main.jsx
rust/llm_chatbot/frontend/src/main.jsx

Fixes the frontend issues with the llm chatbot example. The issue was that the frontend was not adapted to take care of the new backend variant.
The solution to this type incompatibility is to transform the existing type (which is still in use for the frontend) into the needed variant before calling the backend.
This has been tested with copy-pasting the main.jsx into the [Next-Ninja llm-chatbot projects](https://next-icp.ninja/projects/llm-chatbot) and deploying the dapp.

fixed frontend for llm chatbot upgrade to v1

---

rust/parallel_calls/README.md

add: Deploy to ICP Ninja + standardize README

---

rust/backend_only/README.md

standardize README

---

motoko/send_http_get/src/send_http_get_backend/main.mo
motoko/send_http_post/src/send_http_post_backend/main.mo

This PR updates the motoko http outcall examples to use the parenthetical notation instead of the deprecated way to attach cycles.

chore: Use parentheticals to attach cycles

---

rust/unit_testable_rust_canister/src/hello_canister/hello_canister.did
rust/unit_testable_rust_canister/src/hello_canister/src/lib.rs

**Overview**
Fix example to use service_equal, by locating and fixing the underlying error that was preventing its use.

fix: Fix candid test and use service_equal in unit_testable_rust_canister example
